import Link from "next/link";
import { Activity, ArrowUpRight, Bot, ChartNoAxesCombined, CheckCircle2, Clock3, Command, MessageSquareText, Route, ScanSearch, ShieldCheck, WalletCards, Zap } from "lucide-react";

const features = [
  { icon: Activity, title: "Alpha wallet intelligence", text: "Track curated wallets across Ethereum, Base, Arbitrum, Robinhood Chain, Stable, Arc, and Solana. FoundersBot turns movement into a signal you can act on." },
  { icon: MessageSquareText, title: "Plain-English alerts", text: "No more staring at a contract address. NFT mints, buys, sales, token swaps, transfers, marketplace context, artwork, and USD value arrive as readable Discord intelligence when available." },
  { icon: Route, title: "Your feed, your rules", text: "Rank wallets from Tier A to E, filter by the event that matters, and route high-value activity to the right channel. Your server becomes desks, not noise." },
  { icon: WalletCards, title: "Protected copy-minting", text: "CMFSM lets eligible members follow curated wallets or keep a private watchlist, then attempt supported mints from dedicated live wallets with limits and auditability." },
  { icon: ShieldCheck, title: "Safety before speed", text: "Personal RPC coverage, spend caps, daily limits, balance checks, simulation, deduplication, gas ceilings, eco mode, backoff, and a master kill switch keep automation accountable." },
  { icon: Zap, title: "TurboMint control room", text: "Analyze supported OpenSea drops, inspect phases, verify wallet eligibility, choose quantity and spend limits, and schedule a private mint job with a clear event timeline." },
  { icon: ChartNoAxesCombined, title: "PnL with receipts", text: "Generate BlueValleyDAO-branded PnL cards from confirmed FoundersBot mints, with mint cost, wallet counts, valuation mode, estimated position value, and unrealized return." },
  { icon: ScanSearch, title: "A bot that can explain itself", text: "FoundersBot GPT is a member-facing help desk for commands, gas, wallets, access, and workflows. The answer is educational; the transaction still stays in your hands." },
];

export default function FoundersBot() {
  return <main className="page">
    <section className="product-hero"><div className="product-hero-grid"><div><div className="eyebrow">BLUEVALLEYDAO / PRIVATE OPERATING SYSTEM</div><h1>Your community's<br /><span style={{ color: "var(--blue-2)" }}>alpha layer.</span></h1><p>FoundersBot is terminally online: a Discord-native intelligence and automation layer that watches the wallets, mints, and community signals you care about, then makes the next move obvious.</p><div className="hero-actions"><Link className="button primary" href="https://x.com/theweb3proxy">Request access <ArrowUpRight size={15} /></Link><span className="admin-chip">BLUEVALLEYDAO ACCESS</span></div></div><div className="product-preview"><div className="preview-top"><span>FOUNDERSBOT / LIVE SIGNALS</span><span><i className="status-dot" style={{ display: "inline-block", marginRight: 7 }} />ONLINE</span></div><div className="preview-list"><div className="preview-row"><span>Wallets across chains</span><span>07</span></div><div className="preview-row"><span>Transaction language</span><span>READABLE</span></div><div className="preview-row"><span>Priority system</span><span>A - E</span></div><div className="preview-row"><span>Copy-mint guardrails</span><span>ARMED</span></div><div className="preview-row"><span>Member access</span><span>PRIVATE</span></div></div></div></div></section>

    <section className="product-content"><div className="eyebrow">THE DIFFERENCE</div><h2>It does not just<br />watch the chain.</h2><p>It translates the chain into momentum. FoundersBot gives a founder-led community the attention span of a machine and the judgment of a team that knows what matters.</p><div className="feature-grid" style={{ marginTop: 40 }}>{features.map(({ icon: Icon, title, text }) => <div className="feature" key={title}><Icon className="feature-icon" /><h3>{title}</h3><p>{text}</p></div>)}</div></section>

    <section className="product-content signal-section" style={{ paddingTop: 0 }}><div className="product-hero-grid"><div><div className="eyebrow">A NIGHT IN THE DAO</div><h2>While everyone else is asleep, the signal keeps moving.</h2><p>At 2:14 AM, a Tier A wallet mints. FoundersBot can announce the collection, artwork, price, chain, and transaction context in the channel built for that signal. The point is not more notifications. The point is being early with the right information.</p></div><div className="product-preview"><div className="preview-top"><span>WALLET EVENT / TIER A</span><span style={{ color: "var(--cyan)" }}>PRIORITY</span></div><div className="preview-main"><div className="eyebrow">NATURAL-LANGUAGE ALERT</div><strong style={{ display: "block", fontSize: 25, marginTop: 14 }}>Mint detected.<br />Context attached.</strong><div className="preview-bars"><div className="preview-bar"><i style={{ width: "92%" }} /></div><div className="preview-bar"><i style={{ width: "68%" }} /></div><div className="preview-bar"><i style={{ width: "81%" }} /></div></div><span className="hint" style={{ display: "block", marginTop: 18 }}>transaction · collection · value · venue</span></div></div></div></section>

    <section className="product-content" style={{ paddingTop: 0 }}><div className="feature-grid"><div className="feature"><Bot className="feature-icon" /><h3>Community operations</h3><p>Track member activity, send inactivity reminders, rescan history, and give operators clear moderation actions when a server needs housekeeping.</p></div><div className="feature"><Clock3 className="feature-icon" /><h3>Live where it matters</h3><p>Use private commands for gas, wallet state, access, PnL, and copy-mint status. The bot keeps operational answers close to the work.</p></div><div className="feature"><Command className="feature-icon" /><h3>Built for operators</h3><p>Every workflow is designed to reduce hesitation: explicit limits, visible state, private responses, useful links, and a record of what happened.</p></div></div><div className="notice" style={{ marginTop: 34 }}><strong>Private by design.</strong> FoundersBot is available through BlueValleyDAO. Copy-minting is risky automation, not a profit guarantee; failed transactions can still spend gas and lose value.</div></section>

    <section className="product-content" style={{ paddingTop: 0 }}><div className="quote">“You rest. FoundersBot keeps the signal moving.”<br /><span className="mono">— BLUEVALLEYDAO / OPERATING PRINCIPLE</span></div><div className="hero-actions" style={{ marginTop: 26 }}><Link className="button secondary" href="https://x.com/bluevalleylabs">Follow BlueValley Labs <ArrowUpRight size={15} /></Link><span className="hint"><CheckCircle2 size={12} style={{ verticalAlign: "-2px", marginRight: 5, color: "var(--cyan)" }} /> Feature availability varies by server.</span></div></section>
  </main>;
}
