import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Database, Gauge, LockKeyhole, Zap } from "lucide-react";

const chains = ["Ethereum", "Robinhood", "Base", "Arbitrum"];
export default function Home() {
  return <main className="page">
    <section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow">BLUEVALLEY LABS / BLUESUITE 01</div><h1>Tools for the blockchain.<br/><span style={{color:"var(--blue-2)"}}>Built for operators.</span></h1><p>Bluesuite is a collection of purpose-built tools from BLUEVALLEY LABS for managing, analyzing, and operating on-chain workflows.</p><div className="hero-actions"><Link className="button primary" href="#suite">Explore Bluesuite <ArrowRight size={15}/></Link><Link className="button secondary" href="#about">Meet BlueValley Labs <ArrowUpRight size={15}/></Link></div><div className="hero-note"><span className="status-dot"/> Systems designed around how blockchain work actually gets done.</div></div><div className="hero-stage" aria-label="Bluesuite product cards"><Link className="hero-product-card hero-product-card-back" href="/bluehelper"><img src="/bluehelper-card.svg" alt="BlueHelper batch operations card" /></Link><Link className="hero-product-card hero-product-card-mid" href="/foundersbot"><img src="/foundersbot-card.svg" alt="FoundersBot private operating system card" /></Link><Link className="hero-product-card hero-product-card-front" href="/blueshot"><img src="/blueshot-card.svg" alt="Blueshot NFT snapshot card" /></Link><div className="hero-stage-label"><span className="status-dot"/> THREE PRODUCTS / ONE OPERATING SURFACE</div></div></div></section>
    <section className="section" id="suite"><div className="section-head"><div><div className="eyebrow">THE SUITE</div><h2>Infrastructure with<br/>a point of view.</h2></div><p>Small, focused tools for the people responsible for keeping on-chain operations moving.</p></div><div className="suite-grid"><article className="product-card large"><div className="card-kicker">01 / Snapshot infrastructure</div><div className="product-mark">S</div><h3 style={{fontSize:48,marginTop:105}}>Blueshot</h3><p>Snapshot NFT ownership across multiple chains with a single, streamlined workflow.</p><div className="chain-row">{chains.map(c=><span className="chain-badge" key={c}>{c}</span>)}</div><div className="card-footer"><span className="tag">OPERATOR TOOL</span><Link className="arrow-link" href="/blueshot">Open Blueshot <ArrowUpRight size={15}/></Link></div></article><article className="product-card"><div className="card-kicker">02 / Private DAO tooling</div><div className="product-mark">F</div><h3 style={{marginTop:70}}>FoundersBot</h3><p>Seven-chain wallet intelligence, readable Discord alerts, protected copy-minting, and the operating layer behind BlueValleyDAO.</p><div className="card-footer"><span className="tag">DAO EXCLUSIVE</span><Link className="arrow-link" href="/foundersbot">Explore FoundersBot <ArrowUpRight size={15}/></Link></div></article><article className="product-card"><div className="card-kicker">03 / Batch operations</div><div className="product-mark">H</div><h3 style={{marginTop:70}}>BlueHelper</h3><p>The heavy lifting, handled in batches.</p><div className="card-footer"><span className="coming">Coming soon</span><Link className="arrow-link" href="/bluehelper">See what’s next <ArrowUpRight size={15}/></Link></div></article></div><div className="suite-caption">BLUEVALLEY LABS / PURPOSE-BUILT SOFTWARE FOR ON-CHAIN WORK</div></section>
    <section className="section" id="about"><div className="about-grid"><div className="about-image"><img src="/proxy.jpg" alt="Proxy, founder of BLUEVALLEY LABS"/></div><div><div className="eyebrow">THE ECOSYSTEM</div><h2>Built by people<br/>who use it.</h2><p className="muted" style={{fontSize:17,maxWidth:560,marginTop:25}}>BLUEVALLEY LABS builds practical software for people operating on the blockchain. Founded by theweb3proxy.</p><div className="entity-grid"><div className="entity"><div className="label">Proxy</div><p>Medical doctor. Developer. Founder of BLUEVALLEY LABS and BlueValleyDAO. Creator of FoundersBot and Starstruck.</p></div><div className="entity"><div className="label">BLUEVALLEY LABS</div><p>Practical software for people operating on the blockchain.</p><Link className="arrow-link" href="https://x.com/bluevalleylabs">Visit on X <ArrowUpRight size={14}/></Link></div><div className="entity"><div className="label">BlueValleyDAO</div><p>Alpha collective building blockchain tools.<br/><span className="mono">Snapshot · TurboMint · CopyMinter</span></p><Link className="arrow-link" href="https://opensea.io/collection/bluevalley-dao-founders-pass/">OpenSea <ArrowUpRight size={14}/></Link></div></div><div className="quote">“Tools should disappear into the workflow. The work is the point.”<br/><span className="mono">— BLUEVALLEY LABS / PRINCIPLE 01</span></div></div></div></section>
    <section className="section" style={{paddingTop:0}}><div className="feature-grid"><div className="feature"><Database className="feature-icon" size={20}/><h3>Purpose-built</h3><p>Each surface is designed for a specific operational job, without unnecessary noise.</p></div><div className="feature"><LockKeyhole className="feature-icon" size={20}/><h3>Private by default</h3><p>Credentials stay server-side. Access and availability are treated as product features.</p></div><div className="feature"><Gauge className="feature-icon" size={20}/><h3>Fast, precise</h3><p>Clear states, resilient infrastructure, and exports that are ready for the next step.</p></div></div></section>
  </main>;
}
